"""
legacyai.app_pack.generator
~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Generates platform-specific install scripts from app-pack manifests.

Supported outputs
-----------------
- Linux   → Bash shell script (``.sh``)
- Windows → PowerShell script (``.ps1``)
- macOS   → Bash/zsh script (``.sh``)

The generator is **purely deterministic**: the same manifest + options always
produce the same output.  Scripts are written to disk but **never executed**.
"""

from __future__ import annotations

import textwrap
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Dict, List, Optional, Union

# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------

_BANNER_WIDTH = 72

_LINUX_DISTRO_LABELS: Dict[str, str] = {
    "debian_ubuntu": "Debian / Ubuntu / Linux Mint / Zorin OS",
    "fedora_rhel": "Fedora / RHEL / Rocky Linux / AlmaLinux",
    "arch_manjaro": "Arch Linux / Manjaro",
}

_VALID_LINUX_DISTROS = set(_LINUX_DISTRO_LABELS.keys())


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------

def generate_script(
    manifest: Dict[str, Any],
    os_name: str,
    distro: Optional[str] = None,
) -> str:
    """
    Generate an install script string from *manifest*.

    Parameters
    ----------
    manifest:
        Parsed manifest dict (from :func:`legacyai.app_pack.loader.load_manifest`).
    os_name:
        Target OS: ``"linux"``, ``"windows"``, or ``"macos"``.
    distro:
        Linux distro family (``"debian_ubuntu"``, ``"fedora_rhel"``,
        ``"arch_manjaro"``). Required when *os_name* is ``"linux"``.

    Returns
    -------
    str
        The complete script content as a string.

    Raises
    ------
    ValueError
        For invalid *os_name* / *distro* combinations.
    """
    os_name = os_name.lower().strip()
    if os_name not in ("linux", "windows", "macos"):
        raise ValueError(f"Unsupported os_name: '{os_name}'")

    if os_name == "linux":
        if not distro:
            raise ValueError(
                "--distro is required for Linux targets. "
                f"Choose from: {', '.join(sorted(_VALID_LINUX_DISTROS))}"
            )
        distro = distro.lower().strip()
        if distro not in _VALID_LINUX_DISTROS:
            raise ValueError(
                f"Unknown distro '{distro}'. "
                f"Valid choices: {', '.join(sorted(_VALID_LINUX_DISTROS))}"
            )

    if os_name == "windows":
        return _render_powershell(manifest)
    else:
        return _render_bash(manifest, os_name, distro)


def write_script(script: str, output_path: Union[str, Path]) -> Path:
    """
    Write *script* to *output_path*, creating parent directories as needed.

    Parameters
    ----------
    script:
        Script content.
    output_path:
        Destination file path.

    Returns
    -------
    Path
        Resolved path to the written file.
    """
    output_path = Path(output_path).resolve()
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(script, encoding="utf-8")
    return output_path


# ---------------------------------------------------------------------------
# Internal helpers
# ---------------------------------------------------------------------------

def _now_utc() -> str:
    return datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")


def _wrap_comment(text: str, prefix: str = "# ", width: int = 72) -> str:
    """Wrap *text* into comment lines."""
    lines: List[str] = []
    for paragraph in text.strip().splitlines():
        paragraph = paragraph.strip()
        if not paragraph:
            lines.append(prefix.rstrip())
            continue
        for wrapped in textwrap.wrap(paragraph, width=width - len(prefix)):
            lines.append(f"{prefix}{wrapped}")
    return "\n".join(lines)


def _bash_header(manifest: Dict[str, Any], os_name: str, distro: Optional[str]) -> str:
    pack_id = manifest.get("id", "unknown")
    description = manifest.get("description", "").strip()
    licensing = manifest.get("licensing_notes", "").strip()
    platform_label = _LINUX_DISTRO_LABELS.get(distro or "", distro or os_name.title())

    lines = [
        "#!/usr/bin/env bash",
        "#" * _BANNER_WIDTH,
        f"# Legacy64 — App-Pack Install Script",
        f"# Pack     : {pack_id}",
        f"# Platform : {os_name.title()}" + (f" / {platform_label}" if distro else ""),
        f"# Generated: {_now_utc()}",
        "#",
        "# !! THIS SCRIPT WAS GENERATED BY legacyai. DO NOT EDIT MANUALLY. !!",
        "# !! REVIEW BEFORE RUNNING. THIS SCRIPT REQUIRES NETWORK ACCESS.  !!",
        "#",
    ]

    if description:
        lines.append("# Description:")
        lines.extend(_wrap_comment(description, "#   ").splitlines())
        lines.append("#")

    if licensing:
        lines.append("# Licensing:")
        lines.extend(_wrap_comment(licensing, "#   ").splitlines())
        lines.append("#")

    lines.append("#" * _BANNER_WIDTH)
    lines.append("")
    lines.append('set -euo pipefail  # Exit on error, treat unset vars as errors')
    lines.append("")
    return "\n".join(lines)


def _powershell_header(manifest: Dict[str, Any]) -> str:
    pack_id = manifest.get("id", "unknown")
    description = manifest.get("description", "").strip()
    licensing = manifest.get("licensing_notes", "").strip()

    lines = [
        "#" * _BANNER_WIDTH,
        "# Legacy64 - App-Pack Install Script (PowerShell)",
        f"# Pack     : {pack_id}",
        f"# Platform : Windows",
        f"# Generated: {_now_utc()}",
        "#",
        "# !! THIS SCRIPT WAS GENERATED BY legacyai. DO NOT EDIT MANUALLY.  !!",
        "# !! REVIEW BEFORE RUNNING. THIS SCRIPT REQUIRES NETWORK ACCESS.   !!",
        "#",
    ]

    if description:
        lines.append("# Description:")
        lines.extend(_wrap_comment(description, "#   ").splitlines())
        lines.append("#")

    if licensing:
        lines.append("# Licensing:")
        lines.extend(_wrap_comment(licensing, "#   ").splitlines())
        lines.append("#")

    lines.append("#" * _BANNER_WIDTH)
    lines.append("")
    lines.append("$ErrorActionPreference = 'Stop'")
    lines.append("")
    return "\n".join(lines)


def _bash_app_block(app: Dict[str, Any], install_entry: Dict[str, Any]) -> str:
    """Render one app's install block as bash."""
    app_name = app.get("name", app.get("id", "unknown"))
    app_desc = app.get("description", "").strip()
    licensing = app.get("licensing_notes", "").strip()
    post_notes = app.get("post_install_notes", "").strip()

    lines: List[str] = []
    lines.append(f"# {'─' * (_BANNER_WIDTH - 2)}")
    lines.append(f"# {app_name}")
    if app_desc:
        lines.extend(_wrap_comment(app_desc, "# ").splitlines())
    if licensing:
        lines.append("#")
        lines.extend(_wrap_comment(f"License: {licensing}", "# ").splitlines())
    lines.append(f"# {'─' * (_BANNER_WIDTH - 2)}")
    lines.append(f'echo ""')
    lines.append(f'echo "━━━ Installing: {app_name} ━━━"')
    lines.append("")

    pre = install_entry.get("pre_install") or []
    cmds = install_entry.get("commands") or []
    post = install_entry.get("post_install") or []

    for cmd in pre:
        lines.append(cmd)
    for cmd in cmds:
        lines.append(cmd)
    for cmd in post:
        lines.append(cmd)

    if post_notes:
        lines.append("")
        lines.append(f'echo ""')
        lines.append(f'echo "  ℹ️  Notes for {app_name}:"')
        for note_line in post_notes.strip().splitlines():
            note_line = note_line.strip()
            if note_line:
                safe = note_line.replace("'", "'\\''")
                lines.append(f"echo '  {safe}'")
    lines.append("")
    return "\n".join(lines)


def _powershell_app_block(app: Dict[str, Any], install_entry: Dict[str, Any]) -> str:
    """Render one app's install block as PowerShell."""
    app_name = app.get("name", app.get("id", "unknown"))
    app_desc = app.get("description", "").strip()
    licensing = app.get("licensing_notes", "").strip()
    post_notes = app.get("post_install_notes", "").strip()

    lines: List[str] = []
    lines.append(f"# {'─' * (_BANNER_WIDTH - 2)}")
    lines.append(f"# {app_name}")
    if app_desc:
        lines.extend(_wrap_comment(app_desc, "# ").splitlines())
    if licensing:
        lines.append("#")
        lines.extend(_wrap_comment(f"License: {licensing}", "# ").splitlines())
    lines.append(f"# {'─' * (_BANNER_WIDTH - 2)}")
    lines.append(f'Write-Host ""')
    lines.append(f'Write-Host "=== Installing: {app_name} ===" -ForegroundColor Cyan')
    lines.append("")

    pre = install_entry.get("pre_install") or []
    cmds = install_entry.get("commands") or []
    post = install_entry.get("post_install") or []

    for cmd in pre:
        lines.append(cmd)
    for cmd in cmds:
        lines.append(cmd)
    for cmd in post:
        lines.append(cmd)

    if post_notes:
        lines.append("")
        lines.append(f'Write-Host ""')
        lines.append(f'Write-Host "  Notes for {app_name}:" -ForegroundColor Yellow')
        for note_line in post_notes.strip().splitlines():
            note_line = note_line.strip()
            if note_line:
                lines.append(f'Write-Host "  {note_line}"')
    lines.append("")
    return "\n".join(lines)


def _render_bash(
    manifest: Dict[str, Any], os_name: str, distro: Optional[str]
) -> str:
    """Render the full bash/zsh script."""
    parts = [_bash_header(manifest, os_name, distro)]

    apps: List[Dict[str, Any]] = manifest.get("apps", [])
    for app in apps:
        install_entry = _resolve_install_entry(app, os_name, distro)
        if install_entry is None:
            # App has no install info for this platform/distro — skip with comment
            parts.append(
                f"# Skipping '{app.get('name', app.get('id'))}': "
                f"no install entry for this platform/distro.\n"
            )
            continue
        parts.append(_bash_app_block(app, install_entry))

    pack_id = manifest.get("id", "unknown")
    parts.append(
        "\n".join(
            [
                'echo ""',
                'echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"',
                f'echo "  ✅  Legacy64 app-pack \'{pack_id}\' installation complete."',
                'echo "  Review any notes above before starting each application."',
                'echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"',
                'echo ""',
            ]
        )
    )
    return "\n".join(parts)


def _render_powershell(manifest: Dict[str, Any]) -> str:
    """Render the full PowerShell script."""
    parts = [_powershell_header(manifest)]

    apps: List[Dict[str, Any]] = manifest.get("apps", [])
    for app in apps:
        install_entry = _resolve_install_entry(app, "windows", None)
        if install_entry is None:
            parts.append(
                f"# Skipping '{app.get('name', app.get('id'))}': "
                f"no install entry for this platform.\n"
            )
            continue
        parts.append(_powershell_app_block(app, install_entry))

    pack_id = manifest.get("id", "unknown")
    parts.append(
        "\n".join(
            [
                'Write-Host ""',
                'Write-Host "' + "=" * 72 + '" -ForegroundColor Green',
                f'Write-Host "  Legacy64 app-pack \'{pack_id}\' installation complete." -ForegroundColor Green',
                'Write-Host "  Review any notes above before starting each application." -ForegroundColor Green',
                'Write-Host "' + "=" * 72 + '" -ForegroundColor Green',
                'Write-Host ""',
            ]
        )
    )
    return "\n".join(parts)


def _resolve_install_entry(
    app: Dict[str, Any],
    os_name: str,
    distro: Optional[str],
) -> Optional[Dict[str, Any]]:
    """
    Extract the correct ``install_entry`` dict for an app given the target
    OS and distro.

    Returns ``None`` if the app has no entry for this target.
    """
    # Windows / macOS apps use a top-level `install:` key
    if os_name in ("windows", "macos"):
        entry = app.get("install")
        if isinstance(entry, dict):
            return entry
        return None

    # Linux apps use `distros.<distro>` or fall back to top-level `install:`
    if os_name == "linux" and distro:
        distros = app.get("distros") or {}
        if isinstance(distros, dict) and distro in distros:
            entry = distros[distro]
            if isinstance(entry, dict):
                return entry

    # Fallback: check for a platform-agnostic top-level install entry
    fallback = app.get("install")
    if isinstance(fallback, dict):
        return fallback

    return None
